require "prawn"
require "prawn/table"

class FinalSettlementPdf
  def initialize(trip)
    @trip = trip
  end

  def render
    pdf = Prawn::Document.new(page_size: "A4", margin: 40)

    # Header
    pdf.fill_color "0D6EFD"
    pdf.text "TripSplit", size: 26, style: :bold, align: :center
    pdf.fill_color "000000"

    pdf.text "Final Settlement Report",
             size: 16,
             style: :bold,
             align: :center

    pdf.move_down 25

    # Trip Information
    pdf.text "Trip Information", size: 14, style: :bold
    pdf.move_down 8

    details = [
      ["Trip Name", @trip.name],
      ["Destination", @trip.destination],
      ["Start Date", @trip.start_date.to_s],
      ["End Date", @trip.end_date.to_s],
      ["Status", @trip.status.titleize],
      ["Generated On", Time.current.strftime("%d-%m-%Y %I:%M %p")]
    ]

    pdf.table(details,
      width: pdf.bounds.width,
      cell_style: {
        borders: [:top, :bottom, :left, :right],
        padding: 8
      }) do
      columns(0).font_style = :bold
      columns(0).background_color = "F2F2F2"
    end

    pdf.move_down 20

    # Expense Summary
    pdf.text "Expense Summary", size: 14, style: :bold
    pdf.move_down 8

    total_expense = @trip.expenses.sum(:amount)

    pdf.text "Total Expense : Rs. #{format('%.2f', total_expense)}",
             style: :bold

    pdf.move_down 20

    # Settlement Details
    pdf.text "Settlement Details", size: 14, style: :bold
    pdf.move_down 10

    data = [["From", "To", "Amount", "Status"]]

    @trip.settlements.each do |s|
      data << [
        s.payer.name,
        s.receiver.name,
        "Rs. #{format('%.2f', s.amount)}",
        s.status.titleize
      ]
    end

    pdf.table(data,
      header: true,
      width: pdf.bounds.width,
      row_colors: ["FFFFFF", "F8F9FA"]) do

      row(0).background_color = "0D6EFD"
      row(0).text_color = "FFFFFF"
      row(0).font_style = :bold

      self.cell_style = {
        size: 10,
        padding: 8,
        border_width: 0.5
      }
    end

    pdf.move_down 20

    # Summary
    pending = @trip.settlements.pending.count
    completed = @trip.settlements.completed.count

    summary = [
      ["Total Expense", "Rs. #{format('%.2f', total_expense)}"],
      ["Total Settlements", @trip.settlements.count],
      ["Completed", completed],
      ["Pending", pending]
    ]

    pdf.text "Settlement Summary", size: 14, style: :bold
    pdf.move_down 8

    pdf.table(summary,
      width: 300,
      cell_style: {
        padding: 8
      }) do
      columns(0).font_style = :bold
      columns(0).background_color = "E9ECEF"
    end

    pdf.move_down 40

    # Footer
    pdf.stroke_horizontal_rule
    pdf.move_down 10

    pdf.text "Generated by TripSplit",
             align: :center,
             size: 10,
             style: :italic

    pdf.render
  end
end